### ISSUE TITLE
AWS::Lambda::Permission for SNS not working

### ISSUE THREAD

**Issue by devkid** [HyperBrain/serverless-aws-alias#100]
Hi,

I'm trying to create an additional AWS::Lambda::Permission for invocation by SNS topics:
```yaml
resources:
    SNSPermission:
      Type: AWS::Lambda::Permission
      Properties:
        FunctionName:
          Ref: Route53Registration
        Action:    lambda:InvokeFunction
        Principal: sns.amazonaws.com
        SourceArn:
          Fn::Join:
          - ':'
          -
            - 'arn:aws:sns'
            - Ref: 'AWS::Region'
            - Ref: 'AWS::AccountId'
            - '*'
```

But I get the following error:
```
Serverless: Updating alias stack...
Serverless: WARNING: Inappropriate call of provider.request()
 
  Serverless Error ---------------------------------------
 
  [/Resources/SNSPermission/DependsOn/0] 'null' values are not allowed in templates
 
  Stack Trace --------------------------------------------
 
ServerlessError: [/Resources/SNSPermission/DependsOn/0] 'null' values are not allowed in templates
    at BbPromise.fromCallback.catch.err (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:258:33)
From previous event:
    at persistentRequest (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:247:13)
    at doCall (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:205:9)
    at BbPromise (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:216:14)
From previous event:
    at persistentRequest (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:203:38)
    at Object.request.requestQueue.add [as promiseGenerator] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:237:49)
    at Queue._dequeue (/usr/local/lib/node_modules/serverless/node_modules/promise-queue/lib/index.js:149:30)
    at /usr/local/lib/node_modules/serverless/node_modules/promise-queue/lib/index.js:108:18
From previous event:
    at Queue.add (/usr/local/lib/node_modules/serverless/node_modules/promise-queue/lib/index.js:93:16)
    at AwsProvider.request (/usr/local/lib/node_modules/serverless/lib/plugins/aws/provider/awsProvider.js:237:39)
    at AwsAlias.updateAlias (/home/alfred/repos/oa/lambda-asg-sf/route53_registration/node_modules/serverless-aws-alias/lib/updateAliasStack.js:82:25)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
 
  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless
 
  Your Environment Information -----------------------------
     OS:                     linux
     Node Version:           6.11.4
     Serverless Version:     1.25.0
```

This is the relevant part of the generated CloudFormation template:
```json
    "SNSPermission": {
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "FunctionName": {},
        "Action": "lambda:InvokeFunction",
        "Principal": "sns.amazonaws.com",
        "SourceArn": {
          "Fn::Join": [
            ":",
            [
              "arn:aws:sns",
              {
                "Ref": "AWS::Region"
              },
              {
                "Ref": "AWS::AccountId"
              },
              "*",
              "-dev"
            ]
          ]
        }
      },
      "DependsOn": [
        null,
        null
      ]
    }
```

There are three problems:
1. The `FunctionName` property is set to an empty hash.
2. The `SourceArn` property is suffixed with `-dev`.
3. The `DependsOn` attribute is an array of two `null`s.
