### ISSUE TITLE
Cannot rename Lambda functions

### ISSUE THREAD

**Issue by elison-chen** [HyperBrain/serverless-aws-alias#108]
I get a serverless error when renaming Lambda functions.

For example I have the Lambda function:
```
functions:
  readingsEmulator:
    name: readings-emulator-${{self:provider.stage}}
    handler: cloud/readings_emulator/readings_emulator.handler
```
Then I want to change the name (prepending 'gg-')
```
functions:
  readingsEmulator:
    name: gg-readings-emulator-${{self:provider.stage}}
    handler: cloud/readings_emulator/readings_emulator.handler
```

When I run my deploy I get the following error:
```
An error occurred: farm-test - Export farm-test-ReadingsEmulator-LambdaFunctionArn cannot be updated as it is in use by farm-test-test.
```

What can I do to rename the function? Is it supported?
