### ISSUE TITLE
CloudWatchLog event not being assigned to alias

### ISSUE THREAD

**Issue by uladkasach** [HyperBrain/serverless-aws-alias#130]
Currently the `CloudWatchLog` event is not being assigned to the alias of the function, but is being appended the the `unqualified` function always. This event type is defined here: https://serverless.com/framework/docs/providers/aws/events/cloudwatch-log/

For example, running `serverless deploy --alias` with the following configuration included:
```
functions:
  myCloudWatchLog:
    handler: myCloudWatchLog.handler
    events:
      - cloudwatchLog: '/aws/lambda/hello'
```

Results in the CloudWatchLog trigger being assigned to the `unqualified` function in AWS.

Are there any plans to support adding this to the list of events this plugin attaches to an alias?
