### ISSUE TITLE
SQS Queues

### ISSUE THREAD

**Issue by bryanrcampbell** [HyperBrain/serverless-aws-alias#136]
We are using serverless 1.28 to setup lambda triggers. https://serverless.com/framework/docs/providers/aws/events/sqs/

Without the serverless-aws-alias plugin, this functionality works correctly but with it we run into some really odd problems where all functions are subscribed to one of the SQS queues.

I tracked the issue down to this code: https://github.com/HyperBrain/serverless-aws-alias/blob/master/lib/stackops/events.js#L34-L40 - it ends up with an undefined resourceRefName.

A `subscription` the code is looking at looks something like the following (from cloudformation-template-update-stack.json):
```
"ProcessCardTransactionEventSourceMappingSQSCardtransactions": {
      "Type": "AWS::Lambda::EventSourceMapping",
      "DependsOn": "IamRoleLambdaExecution",
      "Properties": {
        "BatchSize": 1,
        "EventSourceArn": "arn:aws:sqs:us-east-1:123456789:card-transactions",
        "FunctionName": {
          "Fn::GetAtt": [
            "ProcessCardTxsLambdaFunction",
            "Arn"
          ]
        },
        "Enabled": "True"
      }
    },
```

Here is a snippet from my serverless.yml
```yml
functions:
  processCardTransaction:
    handler: dist/handlers/cardTransactions
    timeout: 30
    reservedConcurrency: 1
    events:
      - sqs:
          arn: "arn:aws:sqs:us-east-1:123456789:card-transactions"
          batchSize: 1
          enabled: true
  processBankTransaction:
    handler: dist/handlers/bankTransactions
    timeout: 30
    reservedConcurrency: 1
    events:
      - sqs:
          arn: "arn:aws:sqs:us-east-1:123456789:bank-transactions"
          batchSize: 1
          enabled: true
```

Any help here would be appreciated.

Thanks!
