### ISSUE TITLE
Alexa event arn not tied to alias. 

### ISSUE THREAD

**Issue by brettswift** [HyperBrain/serverless-aws-alias#151]
## Expected behaviour: 

serverless.yaml
```
functions:
  mainskill:
    handler: index.handler
    events:
      - alexaSkill:
         appId: amzn1.ask.skill.<skill_id>
https://serverless.com/framework/docs/providers/aws/guide/variables#current-variable-sources
```

deployed with: 
```
serverless deploy --stage main --alias PROD1 -v
```

To result in a PROD1 stage, and the alexa event to be joined to it.  However this is not the case. 

## Actual Behaviour

The alexa skill ID is associated to the lambda at the latest version only.   This results in an error in the alexa console when I try to add  <skill_arn>:PROD1   in the Alexa "Endpoint" because the lambda version does not allow Alexa events. 

Am I mis-configuring this or is this a bug?
