### ISSUE TITLE
API Gateway logs not enabled

### ISSUE THREAD

**Issue by daniel-cottone** [HyperBrain/serverless-aws-alias#92]
I tried updating my serverless config to make use of the API Gateway logging feature, however after deploying I did not see that logging or Cloudwatch metrics were enabled on my stage. I also tried deploying a new alias, but got the same results. I am putting my configuration in the `provider` section:

```
provider:
    name: aws
    runtime: nodejs6.10
    aliasStage:
        dataTraceEnabled: true
        loggingLevel: "INFO"
        metricsEnabled: true
```

Not seeing any errors in the deployment, just no change.
